# Generated by Django 3.2.16 on 2023-03-04 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSchema",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("column_separator", models.CharField(max_length=3)),
                ("string_character", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[("Not Generated", "Not Generated"), ("Processing", "Processing"), ("Ready", "Ready")],
                        default="Not Generated",
                        max_length=32,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="files/")),
                ("filename", models.CharField(max_length=64, null=True)),
                ("created", models.DateField(auto_now_add=True)),
                ("updated", models.DateField(auto_now=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_schemas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataColumn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "column_type",
                    models.CharField(
                        choices=[
                            ("Full Name", "Full Name"),
                            ("Job", "Job"),
                            ("Email", "Email"),
                            ("Domain Name", "Domain Name"),
                            ("Phone Number", "Phone Number"),
                            ("Company Name", "Company Name"),
                            ("Text", "Text"),
                            ("Integer", "Integer"),
                            ("Address", "Address"),
                            ("Date", "Date"),
                        ],
                        max_length=64,
                    ),
                ),
                ("column_name", models.CharField(max_length=255)),
                ("from_value", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("to_value", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("order", models.SmallIntegerField()),
                (
                    "columns",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="data_column", to="csvpro.dataschema"
                    ),
                ),
            ],
        ),
    ]
